language: node_js
node_js:
  - 14

script:
  - npm run update-prices || travis_terminate 1;
  - npm run build

deploy:
    provider: script
    script: npx @cloudflare/wrangler publish
    skip_cleanup: true
    edge: true
    on:
      branch: master
