language: node_js
node_js:
  - 14

script:
  - npm run update-prices || travis_terminate 1;
  - npm run build
#before_deploy:
deploy:
    provider: script
    script: npx @cloudflare/wrangler publish
    skip_cleanup: true
    edge: true
    on:
      branch: master
#   - provider: pages
#     skip_cleanup: true
#     github_token: $ACCESS_TOKEN  # Set in the settings page of your repository, as a secure variable
#     keep_history: true
#     local_dir: build
#     on:
#       branch: master
  # - provider: s3
  #   access_key_id: $AWS_ACCESS_KEY_ID
  #   secret_access_key: $AWS_SECRET_ACCESS_KEY
  #   bucket: tarkov-tools
  #   edge: true
  #   local_dir: build
  #   on:
  #       branch: master
